Did final delierable, Installed checkDisk Plugin to monintor disk IO on Plex Linux Server, and set to notifiy on 10 and 100% usage https://imgur.com/b0ubgt5

diff --git a/usr/local/nagios/libexec/check_log b/usr/local/nagios/libexec/check_log
--- a/usr/local/nagios/libexec/check_log
+++ b/usr/local/nagios/libexec/check_log
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Log file pattern detector plugin for monitoring
+# Log file pattern detector plugin for Nagios
 # Written by Ethan Galstad (nagios@nagios.org)
 # Last Modified: 07-31-1999
 #
@@ -29,15 +29,15 @@
 #
 # If you use this plugin make sure to keep the following in mind:
 #
-#    1.  The "max_attempts" value for the service should be 1, as this will
-#        prevent the monitoring system from retrying the service check (the
+#    1.  The "max_attempts" value for the service should be 1, as this
+#        will prevent Nagios from retrying the service check (the
 #        next time the check is run it will not produce the same results).
 #
-#    2.  The "notify_recovery" value for the service should be 0, so that the
-#        monitoring system does not notify you of "recoveries" for the check.
-#        Since pattern matches in the log file will only be reported once and
-#        not the next time, there will always be "recoveries" for the service,
-#        even though recoveries really don't apply to this type of check.
+#    2.  The "notify_recovery" value for the service should be 0, so that
+#        Nagios does not notify you of "recoveries" for the check.  Since
+#        pattern matches in the log file will only be reported once and not
+#        the next time, there will always be "recoveries" for the service, even
+#        though recoveries really don't apply to this type of check.
 #
 #    3.  You *must* supply a different <old_file_log> for each service that
 #        you define to use this plugin script - even if the different services
@@ -60,24 +60,30 @@
 
 PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
 export PATH
-PROGNAME=`basename $0`
-PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
-REVISION="2.1.2"
+PROGNAME=$(basename "$0")
+PROGPATH=$(echo "$0" | sed -e 's,[\\/][^\\/][^\\/]*$,,')
+REVISION="2.2.1.git"
+PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
 
-. $PROGPATH/utils.sh
+export PATH
+
+. "$PROGPATH"/utils.sh
 
 print_usage() {
     echo "Usage: $PROGNAME -F logfile -O oldlog -q query"
     echo "Usage: $PROGNAME --help"
     echo "Usage: $PROGNAME --version"
+    echo "     Aditional parameter:"
+    echo "        -w (--max_warning) If used, determines the maximum matching value to return as warning, when finding more matching lines than this parameter will return as critical. If not used, will consider as default 0 (any matching will consider as critical)"
+    echo "Usage: $PROGNAME -F logfile -O oldlog -q query -w <number>"
 }
 
 print_help() {
-    print_revision $PROGNAME $REVISION
+    print_revision "$PROGNAME" $REVISION
     echo ""
     print_usage
     echo ""
-    echo "Log file pattern detector plugin for monitoring"
+    echo "Log file pattern detector plugin for Nagios"
     echo ""
     support
 }
@@ -87,7 +93,7 @@ print_help() {
 
 if [ $# -lt 1 ]; then
     print_usage
-    exit $STATE_UNKNOWN
+    exit "$STATE_UNKNOWN"
 fi
 
 # Grab the command line arguments
@@ -100,19 +106,19 @@ while test -n "$1"; do
     case "$1" in
         --help)
             print_help
-            exit $STATE_OK
+            exit "$STATE_OK"
             ;;
         -h)
             print_help
-            exit $STATE_OK
+            exit "$STATE_OK"
             ;;
         --version)
-            print_revision $PROGNAME $REVISION
-            exit $STATE_OK
+            print_revision "$PROGNAME" $REVISION
+            exit "$STATE_OK"
             ;;
         -V)
-            print_revision $PROGNAME $REVISION
-            exit $STATE_OK
+            print_revision "$PROGNAME" $REVISION
+            exit "$STATE_OK"
             ;;
         --filename)
             logfile=$2
@@ -128,6 +134,14 @@ while test -n "$1"; do
             ;;
         -O)
             oldlog=$2
+            shift
+            ;;
+        --max_warning)
+            MAX_WARNING=$2
+            shift
+            ;;
+        -w)
+            MAX_WARNING=$2
             shift
             ;;
         --query)
@@ -149,7 +163,7 @@ while test -n "$1"; do
         *)
             echo "Unknown argument: $1"
             print_usage
-            exit $STATE_UNKNOWN
+            exit "$STATE_UNKNOWN"
             ;;
     esac
     shift
@@ -157,22 +171,22 @@ done
 
 # If the source log file doesn't exist, exit
 
-if [ ! -e $logfile ]; then
+if [ ! -e "$logfile" ]; then
     echo "Log check error: Log file $logfile does not exist!"
-    exit $STATE_UNKNOWN
-elif [ ! -r $logfile ] ; then
+    exit "$STATE_UNKNOWN"
+elif [ ! -r "$logfile" ] ; then
     echo "Log check error: Log file $logfile is not readable!"
-    exit $STATE_UNKNOWN
+    exit "$STATE_UNKNOWN"
 fi
 
 # If the old log file doesn't exist, this must be the first time
 # we're running this test, so copy the original log file over to
 # the old diff file and exit
 
-if [ ! -e $oldlog ]; then
-    cat $logfile > $oldlog
+if [ ! -e "$oldlog" ]; then
+    cat "$logfile" > "$oldlog"
     echo "Log check data initialized..."
-    exit $STATE_OK
+    exit "$STATE_OK"
 fi
 
 # The old log file exists, so compare it to the original log now
@@ -180,31 +194,35 @@ fi
 # The temporary file that the script should use while
 # processing the log file.
 if [ -x /bin/mktemp ]; then
-    tempdiff=`/bin/mktemp /tmp/check_log.XXXXXXXXXX`
+    tempdiff=$(/bin/mktemp /tmp/check_log.XXXXXXXXXX)
 else
-    tempdiff=`/bin/date '+%H%M%S'`
+    tempdiff=$(/bin/date '+%H%M%S')
     tempdiff="/tmp/check_log.${tempdiff}"
-    touch $tempdiff
-    chmod 600 $tempdiff
+    touch "$tempdiff"
+    chmod 600 "$tempdiff"
 fi
 
-diff $logfile $oldlog | grep -v "^>" > $tempdiff
+diff "$logfile" "$oldlog" | grep -v "^>" > "$tempdiff"
 
 # Count the number of matching log entries we have
-count=`grep -c "$query" $tempdiff`
+count=$(grep -c "$query" "$tempdiff")
 
 # Get the last matching entry in the diff file
-lastentry=`grep "$query" $tempdiff | tail -1`
+lastentry=$(grep "$query" "$tempdiff" | tail -1)
 
-rm -f $tempdiff
-cat $logfile > $oldlog
+rm -f "$tempdiff"
+cat "$logfile" > "$oldlog"
 
 if [ "$count" = "0" ]; then # no matches, exit with no error
-    echo "Log check ok - 0 pattern matches found"
+    echo "Log check ok - 0 pattern matches found|match=$count;;;0"
     exitstatus=$STATE_OK
 else # Print total matche count and the last entry we found
-    echo "($count) $lastentry"
-    exitstatus=$STATE_CRITICAL
+    echo "($count) $lastentry|match=$count;;;0"
+    if [ "$MAX_WARNING" ] && [ "$count" -le "$MAX_WARNING" ] ; then
+        exitstatus=$STATE_WARNING
+    else
+        exitstatus=$STATE_CRITICAL
+    fi
 fi
 
-exit $exitstatus
+exit "$exitstatus"
